# -*- coding: utf-8 -*-
"""Lipreading.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vdJaGlTCozt2OLoRK1Or6hZO-TsNYB1O

# AUDIO/VISUAL SPEECH RECOGNITION
"""

!git clone https://github.com/mpc001/auto_avsr.git
!pip install torch torchvision torchaudio pytorch-lightning sentencepiece av
!pip install mediapipe

import sys
sys.path.insert(0, "../")

# Commented out IPython magic to ensure Python compatibility.
# %cd auto_avsr

import os
import torch
import torchaudio
import torchvision

"""## 1. Build an inference pipeline

The InferencePipeline carries out the following three steps:

1. Load audio or video data
2. Run pre-processing functions
3. Run inference
"""

import os
from lightning import ModelModule
from datamodule.transforms import AudioTransform, VideoTransform

import argparse
parser = argparse.ArgumentParser()
args, _ = parser.parse_known_args(args=[])

class InferencePipeline(torch.nn.Module):
    def __init__(self, args, ckpt_path, detector="retinaface"):
        super(InferencePipeline, self).__init__()
        self.modality = args.modality
        if self.modality == "audio":
            self.audio_transform = AudioTransform(subset="test")
        elif self.modality == "video":
            if detector == "mediapipe":
                from preparation.detectors.mediapipe.detector import LandmarksDetector
                from preparation.detectors.mediapipe.video_process import VideoProcess
                self.landmarks_detector = LandmarksDetector()
                self.video_process = VideoProcess(convert_gray=False)
            elif detector == "retinaface":
                from preparation.detectors.retinaface.detector import LandmarksDetector
                from preparation.detectors.retinaface.video_process import VideoProcess
                self.landmarks_detector = LandmarksDetector(device="cuda:0")
                self.video_process = VideoProcess(convert_gray=False)
            self.video_transform = VideoTransform(subset="test")

        ckpt = torch.load(ckpt_path, map_location=lambda storage, loc: storage)
        self.modelmodule = ModelModule(args)
        self.modelmodule.model.load_state_dict(ckpt)
        self.modelmodule.eval()

    def load_video(self, data_filename):
        return torchvision.io.read_video(data_filename, pts_unit="sec")[0].numpy()

    def forward(self, data_filename):
        data_filename = os.path.abspath(data_filename)
        assert os.path.isfile(data_filename), f"data_filename: {data_filename} does not exist."

        if self.modality == "audio":
            audio, sample_rate = self.load_audio(data_filename)
            audio = self.audio_process(audio, sample_rate)
            audio = audio.transpose(1, 0)
            audio = self.audio_transform(audio)
            with torch.no_grad():
                transcript = self.modelmodule(audio)

        if self.modality == "video":
            video = self.load_video(data_filename)
            landmarks = self.landmarks_detector(video)
            video = self.video_process(video, landmarks)
            video = torch.tensor(video)
            video = video.permute((0, 3, 1, 2))
            video = self.video_transform(video)
            with torch.no_grad():
                transcript = self.modelmodule(video)

        return transcript

    def load_audio(self, data_filename):
        waveform, sample_rate = torchaudio.load(data_filename, normalize=True)
        return waveform, sample_rate

    def load_video(self, data_filename):
        return torchvision.io.read_video(data_filename, pts_unit="sec")[0].numpy()

    def audio_process(self, waveform, sample_rate, target_sample_rate=16000):
        if sample_rate != target_sample_rate:
            waveform = torchaudio.functional.resample(
                waveform, sample_rate, target_sample_rate
            )
        waveform = torch.mean(waveform, dim=0, keepdim=True)
        return waveform

"""## 2. Download a video from web"""

!gdown --id 18sLMmOjc4Tvc1oz6mnhPs97Ok8OUNEHW

!ffmpeg -i 00001_vtp.mp4 00001_vtp.wav

"""## 3. VSR inference

### 3.1 Download a pre-trained model
"""

!gdown --id 1r1kx7l9sWnDOCnaFHIGvOtzuhFyFA88_

model_path = "/content/auto_avsr/vsr_trlrs2lrs3vox2avsp_base.pth"

"""### 3.2 Initialize VSR pipeline"""

setattr(args, 'modality', 'video')
pipeline = InferencePipeline(args, model_path, detector="mediapipe")

"""### 3.3 Run inference"""

transcript = pipeline("/content/auto_avsr/00001_vtp.mp4")
print(transcript)

"""## Can we convert this to Speech?"""

!pip install chatterbox-tts

import torchaudio as ta
from chatterbox.tts import ChatterboxTTS

model = ChatterboxTTS.from_pretrained(device="cuda")

text = "I'D LIKE YOU TO IMAGINE FOR A MOMENT THAT YOU'RE SOLDIER IN THE HEAT OF BATTLE MAYBE YOU'RE A ROMAN FRONT SOLDIER"
wav = model.generate(text)
ta.save("test-1.wav", wav, model.sr)

# prompt: play an audio

from IPython.display import Audio
Audio("test-1.wav")

AUDIO_PROMPT_PATH = "/content/auto_avsr/00001_vtp.wav"
wav = model.generate(text, audio_prompt_path=AUDIO_PROMPT_PATH)
ta.save("test-2.wav", wav, model.sr)

Audio("test-2.wav")